a <- read.table('C:\\Users\\Nixon Joel\\Desktop\\coursera\\Exploratory Data Analysis\\household_power_consumption.txt', sep=';', header=T, colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),
                na.strings='?')
a$DateTime <- strptime(paste(a$Date, a$Time),"%d/%m/%Y %H:%M:%S")
b <- subset(a,as.Date(DateTime) >= as.Date("2007-02-01") & as.Date(DateTime) <= as.Date("2007-02-02"))
png("plot3.png", height=480, width=480)
plot(b$DateTime, b$Sub_metering_1, xlab="", ylab="Energy sub metering")
lines(b$DateTime, data$Sub_metering_1)
lines(b$DateTime, data$Sub_metering_2, col='red')
lines(b$DateTime, data$Sub_metering_3, col='blue')
legend('topright', c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c('black', 'red', 'blue'))
dev.off()