a <- read.table('C:\\Users\\Nixon Joel\\Desktop\\coursera\\Exploratory Data Analysis\\household_power_consumption.txt', sep=';', header=T, colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),
                na.strings='?')
a$DateTime <- strptime(paste(a$Date, a$Time),"%d/%m/%Y %H:%M:%S")
b <- subset(a,as.Date(DateTime) >= as.Date("2007-02-01") & as.Date(DateTime) <= as.Date("2007-02-02"))
png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(b$DateTime, b$Global_active_power, xlab="", pch=NA, ylab="Global Active Power (kilowatts)")
lines(b$DateTime, b$Global_active_power, pch=NA)
plot(b$DateTime, b$Voltage, ylab="Voltage", xlab="datetime", pch=NA)
lines(b$DateTime, b$Voltage, pch=NA)
plot(b$DateTime, b$Sub_metering_1, xlab="", pch=NA, ylab="Energy sub metering")
lines(b$DateTime, b$Sub_metering_1, pch=NA)
lines(b$DateTime, b$Sub_metering_2, col='red', pch=NA)
lines(b$DateTime, b$Sub_metering_3, col='blue', pch=NA)
legend('topright', c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c('black', 'red', 'blue'), bty = 'n')
with(b, plot(DateTime, Global_reactive_power, xlab='datetime',pch=NA))
with(b, lines(DateTime, Global_reactive_power,pch=NA))
dev.off()
